# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0005_auto_20170725_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='Marketplace.Tag'),
        ),
    ]
