# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0008_auto_20170726_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
