# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0012_item_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='course_name',
            field=models.CharField(blank=True, default='none', max_length=30),
        ),
    ]
