# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0014_auto_20170813_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Amount', models.BooleanField(default=True)),
                ('amount_offer', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_post', to='Marketplace.Item')),
                ('item_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketplace.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketplace.Profile')),
            ],
        ),
    ]
