# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0015_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Marketplace.Item'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
