# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0016_auto_20170814_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='amount_offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_Amount',
            field=models.BooleanField(default=False),
        ),
    ]
